export enum FilterType {
  PUBLISHER = 'PUBLISHER',
  TOPICS = 'TOPICS',
  CONTENT_TYPE = 'CONTENT_TYPE',
  DURATION = 'DURATION',
  DIFFICULTY = 'DIFFICULTY',
  KEYWORDS = 'KEYWORDS',
  SEARCH = 'SEARCH',
}
