// These settings represent the most used. There may be some legacy settings missing from this enum
// If that is the case, retrieve the Raw settings and enumerate those
export enum TenantSettingType {
  AllowEmailNotifications = "ALLOW_EMAIL_NOTIFICATIONS",
  ADSyncType = "CLOUD_SYNC_TYPE",
  CompanyLogoClassic="COMPANY_LOGO",
  CompanyLogoUrl="COMPANY_LOGO_NAVIGATE_URL",
  CompanyLogoLarge="COMPANY_LOGO_PEAK_DISPLAY",
  CompanyLogoSmall="COMPANY_LOGO_PEAK_LARGE",
  CompanyNews="COMPANY_NEWS",
  ActiveTheme="COMPANY_THEME",
  ContentHeaderImage="CONTENT_HEADER",
  AllowDeclareExpertise="DB_DECLAREEXPERT",
  DiagramFont="DIAGRAM_FONT",
  DiagramFontBold="DIAGRAM_FONT_BOLD",
  DiagramFontItalid="DIAGRAM_FONT_ITALIC",
  DiagramFontUnderline="DIAGRAM_FONT_UNDERLINE",
  DiagramDisplayDepartmentLabel="DISPLAY_DEPARTMENTS",
  DiagramDisplayRoleLabel="DISPLAY_ROLES",
  AllowContentDownload="DOWNLOAD_VIEW",
  SendCredentialsNote="EMAIL_PASSWORD_NOTE",
  ExtendedSearchDesc="EXT_SEARCH_DESC",
  ExtendedSearchTitle="EXT_SEARCH_TITLE",
  ExtendedSearchUrl="EXT_SEARCH_URL",
  CompanyLogoHide="HIDE_LOGO",
  CertificateTemplate="LP_CERTIFICATE",
  WFTreeLPDisplay="LPWF_DISPLAY",
  PeakConfigEnabled="PEAK_CONFIG_ENABLED",
  PeakUserExperienceEnabled="PEAK_USER_ENABLED",
  DiagramProcessBorderColor="PROCESS_BORDER_COLOR",
  DiagramProcessFillColor1="PROCESS_FILL_COLOR1",
  DiagramProcessFillColor2="PROCESS_FILL_COLOR2",
  DiagramProcessGradient="PROCESS_GRADIENT",
  DiagramProcessTextColor="PROCESS_TEXT_COLOR",
  ADSyncUserImages="SyncImages",
  DiagramTaskBorderColor="TASK_BORDER_COLOR",
  DiagramTaskFillColor1="TASK_FILL_COLOR1",
  DiagramTaskFillColor2="TASK_FILL_COLOR2",
  DiagramTaskGradient="TASK_GRADIENT",
  DiagramTaskTextColor="TASK_TEXT_COLOR",
  ShowExtendedSearch="USE_EXT_SEARCH",
  WFTreeDisplay="WF_DISPLAY"
}
